#define BS_NAME    @"Beardie"
#define BS_GROUP    @"5F2QV47DGC.com.calm_apps.mac.beardie"
#define BS_BUILD    @"53"
#define BS_SAFARI_TECHPREVIEW_ID    @"com.apple.SafariTechnologyPreview"
#define BS_VERSION    @"3.0.2"
#define BS_DEFAULT_CHROME_BUNDLE_ID    @"com.google.Chrome"
#define BS_STRATEGY_EXTENSION    @"bsstrategy"
#define BS_NATIVE_MESSAGING_CONNECTOR_BUNDLE_ID    @"com.calm_apps.mac.beardie.nm.connector"
#define BS_CONTROLLER_BUNDLE_ID    @"com.calm_apps.mac.beardie.controllers"
#define BS_HOMEPAGE    @"https://github.com/Stillness-2/beardie"
#define BS_NATIVE_MESSAGING_CONNECTOR_NAME    @"beardie-nm-connector"
#define BS_SAFARI_EXTENSION_BUNDLE_ID    @"com.calm_apps.mac.beardie.safari.extension"
#define BS_COPYRIGHT    @"Copyright © 2019 Beardie. All rights reserved."
#define BS_CHROME_EXTENSION_ID    @"kcbddjdbhggfejihipchloknandfnkgb"
#define BS_BUNDLE_ID    @"com.calm_apps.mac.beardie"
#define BS_DEFAULT_SAFARI_BUBDLE_ID    @"com.apple.Safari"
