#define BS_UNSUPPORTED_STRATEGY_URL_FORMAT    @"https://raw.githubusercontent.com/beardedspice/BS-Strategies/master/%@.bsstrategy"
#define BS_RESTARTER_BUNDLE_ID    @"com.calm-apps.mac.beardie.restarter"
#define BS_NAME    @"Beardie"
#define BS_GROUP    @"5F2QV47DGC.com.calm-apps.mac.beardie"
#define BS_LAUNCHER_BUNDLE_ID    @"com.calm-apps.mac.beardie.launcher"
#define BS_ORG_ID    @"com.calm-apps.mac"
#define BS_BUILD    @"65"
#define BS_TEAM    @"5F2QV47DGC"
#define BS_SAFARI_TECHPREVIEW_ID    @"com.apple.SafariTechnologyPreview"
#define BS_VERSION    @"3.0.6 alpha"
#define BS_DEFAULT_CHROME_BUNDLE_ID    @"com.google.Chrome"
#define BS_STRATEGY_JSON_URL    @"https://raw.githubusercontent.com/Stillness-2/beardie/master/BeardedSpice/MediaStrategies/manifest.json"
#define BS_STRATEGY_EXTENSION    @"bsstrategy"
#define BS_NATIVE_MESSAGING_CONNECTOR_BUNDLE_ID    @"com.calm_apps.mac.beardie.nm.connector"
#define BS_UNSUPPORTED_STRATEGY_REPO_URL    @"https://github.com/beardedspice/BS-Strategies"
#define BS_STRATEGY_URL_FORMAT    @"https://raw.githubusercontent.com/Stillness-2/beardie/master/BeardedSpice/MediaStrategies/%@.js"
#define BS_CONTROLLER_BUNDLE_ID    @"com.calm-apps.mac.beardie.controllers"
#define BS_RESTARTER_NAME    @"beardie_restarter"
#define BS_HOMEPAGE    @"https://github.com/Stillness-2/beardie"
#define BS_NATIVE_MESSAGING_CONNECTOR_NAME    @"beardie-nm-connector"
#define BS_CHROME_EXTENSION_ID_DEV    @"kfecbffboepnaccakdfaionjkemmmljp"
#define BS_SAFARI_EXTENSION_BUNDLE_ID    @"com.calm-apps.mac.beardie.safari.extension"
#define BS_COPYRIGHT    @"Copyright © 2020 Beardie. All rights reserved."
#define BS_CHROME_EXTENSION_ID    @"kcbddjdbhggfejihipchloknandfnkgb"
#define BS_BUNDLE_ID    @"com.calm-apps.mac.beardie"
#define BS_UNSUPPORTED_STRATEGY_JSON_URL    @"https://raw.githubusercontent.com/beardedspice/BS-Strategies/master/manifest.json"
#define BS_SIGN    @"Developer ID Application: Roman Sokolov (5F2QV47DGC)"
#define BS_DEFAULT_SAFARI_BUBDLE_ID    @"com.apple.Safari"
